import { Wallet } from '../../shared/wallet.js';
import { mountHud } from '../../shared/hud.js';
import { saveScore, getBestScore } from '../../shared/records.js';
import { Audio } from '../../shared/audio.js';
import { unlockAchievement } from '../../shared/achievements.js';
import '../../shared/skins.js';
import '../../shared/auth.js';
import { showTutorialOnce } from '../../shared/tutorial.js';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),hud=mountHud('asteroids',document.querySelector('#score'),document.querySelector('#wallet-count')),status=document.querySelector('#status');
const W=640,H=560;let ship,bullets,rocks,score,lives,wave,running,paused,frame,lastTime,shotAt,destroyed,lifeLost;
function wrap(value,max){return (value+max)%max;}
function makeRock(size,x= Math.random()*W,y=Math.random()*H){const angle=Math.random()*Math.PI*2,speed=.5+Math.random()*1.2;return{x,y,size,dx:Math.cos(angle)*speed,dy:Math.sin(angle)*speed,angle:Math.random()*6.28};}
function newWave(){wave++;rocks=[];for(let i=0;i<3+wave;i++){let rock;do{rock=makeRock(3)}while(Math.hypot(rock.x-ship.x,rock.y-ship.y)<130);rocks.push(rock);}if(wave===1)unlockAchievement('asteroids-wave');if(wave>=5)unlockAchievement('asteroids-five');}
function reset(){cancelAnimationFrame(frame);ship={x:W/2,y:H/2,angle:-Math.PI/2,dx:0,dy:0};bullets=[];score=0;lives=3;wave=0;destroyed=0;lifeLost=false;running=false;paused=false;shotAt=0;newWave();draw();status.textContent='PULSA UNA FLECHA O ESPACIO';}
function draw(){ctx.fillStyle='#050717';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#fff4d6';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(ship.x+Math.cos(ship.angle)*18,ship.y+Math.sin(ship.angle)*18);ctx.lineTo(ship.x+Math.cos(ship.angle+2.5)*14,ship.y+Math.sin(ship.angle+2.5)*14);ctx.lineTo(ship.x+Math.cos(ship.angle-2.5)*14,ship.y+Math.sin(ship.angle-2.5)*14);ctx.closePath();ctx.stroke();bullets.forEach(b=>{ctx.fillStyle='#ffe66d';ctx.fillRect(b.x-2,b.y-2,4,4)});rocks.forEach(r=>{ctx.strokeStyle=r.size===3?'#ff4f9a':r.size===2?'#ff8b3d':'#23e7d7';ctx.beginPath();ctx.arc(r.x,r.y,r.size*13,0,Math.PI*2);ctx.stroke()});hud.setScore(score);document.querySelector('#best').textContent=String(getBestScore('asteroids')).padStart(4,'0');}
function end(){running=false;cancelAnimationFrame(frame);saveScore('asteroids',score,{bronze:500,silver:1600,gold:4500});Wallet.add(Math.max(1,Math.floor(score/220)));Audio.playSfx('coin');Audio.playSfx('gameover');status.textContent=`GAME OVER / OLEADA ${wave}`;draw();}
function splitRock(index){const rock=rocks[index];rocks.splice(index,1);if(rock.size>1){rocks.push(makeRock(rock.size-1,rock.x,rock.y),makeRock(rock.size-1,rock.x,rock.y));}const points=rock.size===3?20:rock.size===2?50:100;score+=points;destroyed++;if(destroyed>=10&&!lifeLost)unlockAchievement('asteroids-hunter');Audio.playSfx('eat');}
function loop(time){if(!running||paused)return;const delta=Math.min(32,time-lastTime||16);lastTime=time;if(keys.ArrowLeft)ship.angle-=.005*delta;if(keys.ArrowRight)ship.angle+=.005*delta;if(keys.ArrowUp){ship.dx+=Math.cos(ship.angle)*.004*delta;ship.dy+=Math.sin(ship.angle)*.004*delta;}ship.dx*=.995;ship.dy*=.995;ship.x=wrap(ship.x+ship.dx*delta,W);ship.y=wrap(ship.y+ship.dy*delta,H);bullets.forEach(b=>{b.x=wrap(b.x+b.dx*delta,W);b.y=wrap(b.y+b.dy*delta,H);b.life-=delta});bullets=bullets.filter(b=>b.life>0);rocks.forEach(r=>{r.x=wrap(r.x+r.dx*delta,W);r.y=wrap(r.y+r.dy*delta,H)});for(let bi=bullets.length-1;bi>=0;bi--){const b=bullets[bi],hit=rocks.findIndex(r=>Math.hypot(b.x-r.x,b.y-r.y)<r.size*13);if(hit>=0){bullets.splice(bi,1);splitRock(hit);}}if(rocks.some(r=>Math.hypot(ship.x-r.x,ship.y-r.y)<r.size*13+10)){lives--;lifeLost=true;ship={x:W/2,y:H/2,angle:-Math.PI/2,dx:0,dy:0};if(!lives)return end();}if(!rocks.length)newWave();draw();frame=requestAnimationFrame(loop);}
function begin(){if(!running){running=true;paused=false;status.textContent='EN JUEGO';frame=requestAnimationFrame(loop);}}
function togglePause(){if(!running)return;paused=!paused;status.textContent=paused?'PAUSA':'EN JUEGO';if(!paused){lastTime=performance.now();frame=requestAnimationFrame(loop)}draw();}
const keys={};document.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();togglePause();return}if(!['ArrowLeft','ArrowRight','ArrowUp',' '].includes(e.key))return;e.preventDefault();if(e.key===' ')begin(),Date.now()-shotAt>250&&(bullets.push({x:ship.x+Math.cos(ship.angle)*18,y:ship.y+Math.sin(ship.angle)*18,dx:Math.cos(ship.angle)*.45+ship.dx,dy:Math.sin(ship.angle)*.45+ship.dy,life:1300}),shotAt=Date.now(),Audio.playSfx('click'));else keys[e.key]=true;begin();});document.addEventListener('keyup',e=>{keys[e.key]=false});document.querySelector('#restart').addEventListener('click',reset);showTutorialOnce('asteroids','<p>FLECHAS: ROTAR Y ACELERAR<br>ESPACIO: DISPARAR<br>ESC: PAUSA</p>');reset();
