import { mountHud } from '../../shared/hud.js';
import { getBestScore, saveScore } from '../../shared/records.js';
import { Audio } from '../../shared/audio.js';
import '../../shared/skins.js';
import '../../shared/auth.js';
import { unlockAchievement } from '../../shared/achievements.js';
import { showTutorialOnce } from '../../shared/tutorial.js';
import { submitScore } from '../../shared/leaderboard.js';
import { recordGameStart, recordGameEnd } from '../../shared/stats.js';
const layouts = [['1111111111','1111111111','1111111111','1111111111','1111111111'],['1100110011','1111111111','0111111110','1111111111','1100110011','1111111111'],['1010101010','1111111111','1111111111','0111111110','1111111111','1010101010','1111111111']];
const colors = ['#f04462','#ff8b3d','#ffe66d','#62e889','#23e7d7'];
	const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d');
	const hud = mountHud('breakout', document.querySelector('#score'), document.querySelector('#wallet-count')); const status = document.querySelector('#status');
	let paddle, balls, bricks, powerups, score, lives, running, frame, destroyed, rebounds, paused, level, layoutIndex, combo, active, lastTime;
	function buildLevel() { const pattern = layouts[layoutIndex % layouts.length]; bricks = pattern.map((row, y) => [...row].map((cell, x) => cell === '1' ? { x:28+x*60, y:45+y*25, w:52, h:15, value:(pattern.length-y)*10, color:colors[y%colors.length], hits:level >= 3 && y < 2 ? 3 : level >= 2 && y % 2 === 0 ? 2 : 1 } : null)); }
	function newBall(stuck = false) { return { x:paddle.x+paddle.w/2, y:paddle.y-10, dx:(Math.random()>.5?1:-1)*3, dy:-4, r:8, stuck }; }
	function reset() { cancelAnimationFrame(frame); recordGameStart('breakout'); paddle={x:270,y:450,w:100,h:13}; balls=[newBall()]; powerups=[]; score=0;destroyed=0;rebounds=0;lives=3;level=1;layoutIndex=0;combo=0;active={wideUntil:0,slowUntil:0,stickyUntil:0,sticky:false};paused=false;running=false;buildLevel();draw();status.textContent='PULSA UNA FLECHA O MUEVE EL RATON'; }
 function end(won=false) { running=false;cancelAnimationFrame(frame);saveScore('breakout',score,{bronze:300,silver:900,gold:2200});submitScore('breakout',score).catch(() => {});recordGameEnd('breakout');hud.awardCoins(score,180);status.textContent=won?'TABLERO LIMPIO':'GAME OVER';Audio.playSfx(won?'levelup':'gameover');draw(); }
function activate(type) { const now=Date.now();if(type==='wide')active.wideUntil=now+9000;if(type==='slow')active.slowUntil=now+8000;if(type==='sticky'){active.stickyUntil=now+9000;active.sticky=true;}if(type==='multi'&&balls[0])balls.push({...balls[0],dx:-balls[0].dx});status.textContent=`POWER ${type.toUpperCase()}`;Audio.playSfx('levelup'); }
function dropPowerup(brick) { if(Math.random()>.1)return;const types=[['wide','#23e7d7','W'],['slow','#62e889','S'],['multi','#ff4f9a','M'],['sticky','#ffe66d','G']];const [type,color,label]=types[Math.floor(Math.random()*types.length)];powerups.push({x:brick.x+brick.w/2,y:brick.y,type,color,label}); }
function hitBrick(ball) { for(const row of bricks)for(let i=0;i<row.length;i++){const brick=row[i];if(brick&&ball.x+ball.r>brick.x&&ball.x-ball.r<brick.x+brick.w&&ball.y+ball.r>brick.y&&ball.y-ball.r<brick.y+brick.h){brick.hits--;ball.dy*=-1;if(brick.hits<=0){row[i]=null;destroyed++;combo++;score+=brick.value*combo;dropPowerup(brick);if(destroyed>=10)unlockAchievement('breakout-bricks');status.textContent=combo>1?`COMBO x${combo}`:'BLOQUE ROTO';}else status.textContent=`RESISTENTE ${brick.hits}`;Audio.playSfx('eat');return true;}}return false; }
function loop(time=performance.now()) { if(!running||paused)return;const elapsed=Math.min(32,time-lastTime||16);lastTime=time;const now=Date.now();const width=now<active.wideUntil?150:100;paddle.x=Math.max(0,Math.min(640-width,paddle.x));powerups.forEach(p=>p.y+=2);powerups=powerups.filter(p=>{if(p.y+9>=paddle.y&&p.x>=paddle.x&&p.x<=paddle.x+width){activate(p.type);return false}return p.y<480});if(active.stickyUntil&&now>=active.stickyUntil){active.sticky=false;active.stickyUntil=0;}for(let index=balls.length-1;index>=0;index--){const ball=balls[index];if(ball.stuck){ball.x=paddle.x+width/2;ball.y=paddle.y-10;continue;}const factor=now<active.slowUntil?.65:1;ball.x+=ball.dx*factor*elapsed/16;ball.y+=ball.dy*factor*elapsed/16;if(ball.x<ball.r||ball.x>640-ball.r)ball.dx*=-1;if(ball.y<ball.r)ball.dy*=-1;if(ball.y>480){balls.splice(index,1);continue;}if(ball.y+ball.r>=paddle.y&&ball.y-ball.r<=paddle.y+paddle.h&&ball.x>paddle.x&&ball.x<paddle.x+width){ball.dy=-Math.abs(ball.dy);ball.dx+=(ball.x-(paddle.x+width/2))/35;ball.dx=Math.max(-7,Math.min(7,ball.dx));rebounds++;combo=0;if(rebounds>=20)unlockAchievement('breakout-rally');if(active.sticky)ball.stuck=true;Audio.playSfx('click');}hitBrick(ball);}if(!balls.length){lives--;combo=0;rebounds=0;if(!lives){end();return}balls=[newBall()];}if(bricks.flat().every(b=>!b)){unlockAchievement('breakout-clear');level++;layoutIndex++;buildLevel();balls=[newBall()];combo=0;status.textContent=`NIVEL ${level}`;Audio.playSfx('levelup');}draw();frame=requestAnimationFrame(loop);}
	function draw() { ctx.fillStyle='#050717';ctx.fillRect(0,0,640,480);bricks.flat().filter(Boolean).forEach(b=>{ctx.fillStyle=b.hits===3?'#b64cce':b.hits===2?'#d5a83d':b.color;ctx.fillRect(b.x,b.y,b.w,b.h);if(b.hits>1){ctx.fillStyle='#11142b';ctx.fillRect(b.x+b.w/2-1,b.y+3,2,b.h-6);}});powerups.forEach(p=>{ctx.fillStyle=p.color;ctx.fillRect(p.x-9,p.y-9,18,18);ctx.fillStyle='#11142b';ctx.font='9px monospace';ctx.textAlign='center';ctx.fillText(p.label,p.x,p.y+3);});const width=Date.now()<active.wideUntil?150:100;ctx.fillStyle=active.wideUntil?'#23e7d7':'#ffe66d';ctx.fillRect(paddle.x,paddle.y,width,paddle.h);balls.forEach(ball=>{ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r,0,Math.PI*2);ctx.fillStyle=active.slowUntil?'#62e889':'#fff4d6';ctx.fill();});hud.setScore(score);document.querySelector('#best').textContent=String(getBestScore('breakout')).padStart(4,'0');}
function begin(){if(!running){running=true;status.textContent='EN JUEGO';loop();}}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();if(running){paused=!paused;status.textContent=paused?'PAUSA':'EN JUEGO';if(paused)cancelAnimationFrame(frame);else loop();}return;}if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();begin();paddle.x=Math.max(0,Math.min(640-paddle.w,paddle.x+(e.key==='ArrowLeft'?-35:35)));});canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();paddle.x=Math.max(0,Math.min(640-paddle.w,(e.clientX-r.left)/r.width*640-paddle.w/2));begin();});document.querySelector('#restart').addEventListener('click',reset);showTutorialOnce('breakout','<p>FLECHAS O RATON: PALA<br>ESC: PAUSA</p>');reset();
