import { mountHud } from '../../shared/hud.js';
import { getBestScore, saveScore } from '../../shared/records.js';
import { Audio } from '../../shared/audio.js';
import '../../shared/skins.js';
import '../../shared/auth.js';
import { unlockAchievement } from '../../shared/achievements.js';
import { showTutorialOnce } from '../../shared/tutorial.js';
const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d');
const hud = mountHud('breakout', document.querySelector('#score'), document.querySelector('#wallet-count')); const status = document.querySelector('#status');
let paddle, ball, bricks, score, lives, running, frame, destroyed, rebounds, paused;
function reset() { cancelAnimationFrame(frame); paddle={x:270,y:450,w:100,h:13}; ball={x:320,y:420,dx:3,dy:-4,r:8}; bricks=Array.from({length:5},(_,row)=>Array.from({length:10},(_,col)=>({x:28+col*60,y:45+row*25,w:52,h:15,value:(5-row)*10,color:['#f04462','#ff8b3d','#ffe66d','#62e889','#23e7d7'][row]}))); score=0;destroyed=0;rebounds=0;lives=3;running=false;paused=false;draw();status.textContent='PULSA UNA FLECHA O MUEVE EL RATON';}
function draw() { ctx.fillStyle='#050717';ctx.fillRect(0,0,640,480); bricks.flat().filter(Boolean).forEach(b=>{ctx.fillStyle=b.color;ctx.fillRect(b.x,b.y,b.w,b.h)});ctx.fillStyle='#ffe66d';ctx.fillRect(paddle.x,paddle.y,paddle.w,paddle.h);ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r,0,Math.PI*2);ctx.fillStyle='#fff4d6';ctx.fill();hud.setScore(score);document.querySelector('#best').textContent=String(getBestScore('breakout')).padStart(4,'0');}
function end(won=false) { running=false;cancelAnimationFrame(frame);saveScore('breakout',score,{bronze:300,silver:900,gold:2200});hud.awardCoins(score,180);status.textContent=won?'TABLERO LIMPIO':'GAME OVER';Audio.playSfx(won?'levelup':'gameover');draw(); }
function loop() { if(!running)return; ball.x+=ball.dx;ball.y+=ball.dy;if(ball.x<ball.r||ball.x>640-ball.r)ball.dx*=-1;if(ball.y<ball.r)ball.dy*=-1;if(ball.y>480){lives--;rebounds=0;if(!lives){end();return}ball={x:paddle.x+paddle.w/2,y:420,dx:3,dy:-4};}if(ball.y+ball.r>=paddle.y&&ball.y-ball.r<=paddle.y+paddle.h&&ball.x>paddle.x&&ball.x<paddle.x+paddle.w){ball.dy=-Math.abs(ball.dy);ball.dx+=(ball.x-(paddle.x+paddle.w/2))/35;rebounds++;if(rebounds>=20)unlockAchievement('breakout-rally');Audio.playSfx('click');}for(const row of bricks)for(let i=0;i<row.length;i++){const b=row[i];if(b&&ball.x+ball.r>b.x&&ball.x-ball.r<b.x+b.w&&ball.y+ball.r>b.y&&ball.y-ball.r<b.y+b.h){row[i]=null;destroyed++;if(destroyed>=10)unlockAchievement('breakout-bricks');ball.dy*=-1;score+=b.value;ball.dx*=1.005;Audio.playSfx('eat');}}if(bricks.flat().every(b=>!b)){unlockAchievement('breakout-clear');end(true);return}draw();frame=requestAnimationFrame(loop);}
function begin(){if(!running){running=true;status.textContent='EN JUEGO';loop();}}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();if(running){paused=!paused;status.textContent=paused?'PAUSA':'EN JUEGO';if(paused)cancelAnimationFrame(frame);else loop();}return;}if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();begin();paddle.x=Math.max(0,Math.min(640-paddle.w,paddle.x+(e.key==='ArrowLeft'?-35:35)));});canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();paddle.x=Math.max(0,Math.min(640-paddle.w,(e.clientX-r.left)/r.width*640-paddle.w/2));begin();});document.querySelector('#restart').addEventListener('click',reset);showTutorialOnce('breakout','<p>FLECHAS O RATON: PALA<br>ESC: PAUSA</p>');reset();
